config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do 
  		get "signin" => 'devise/sessions#new'
  		delete "signout" => 'devise/sessions#destroy'
  		get "signup" => 'devise/registrations#new'
  	end
	root 'pages#home'
	get 'about' => 'pages#about'
	get 'contactus' => 'pages#contactus'
  get 'profile' => 'pages#profile'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  	end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Project Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Profile", profile_path, class: "nav-link" %></
         li>
          <% if user_signed_in? %>
           <li class="nav-item pull-md-right"><%= link_to "Log Out",
           signout_path, method: :delete, class: "nav-link" %></li>
           <% else %>
             <li class="nav-item pull-md-right"><%= link_to "Sign In",
               signin_path, class: "nav-link" %></li>
           <li class="nav-item pull-md-right"><%= link_to "Sign Up",
               signup_path, class: "nav-link btn btn-primary" %></li>
           <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
    <%= content_tag(:div, message, class: "alert alert #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© HutchTec Design</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contactus.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
    </div>
		</div>
	</div>


<h1>Contact-Us</h1>
<h2>HutchTec Project Rails</h2>
<p>Phone: 0498244903</p>
<p>Email: tim.hutch.work@gmail.com</p>
<p>I will add a new Twitter handle in future and review this training sessions</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome Back!</h1>
        </div>
    </div>
<% else %>
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to my website!</h1>
        <p>This is project rails, this is my first Ruby on Rails project that is a prototype to secure funding.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
            %>
        <% end %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>World class HRIS system that will help governements with complainace. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>OHS system that integrates into HRIS. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>IT asset tracking that will integrate with HRIS. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>

app/views/pages/profile.html.erb
<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>{first name}Welcome Back!</h1>
        </div>
    </div>
<% else %>
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>{name}Welcome to your profile</h1>
        <p>Please keep your details up to date.</p>
        <%= link_to "Edit Profile »", "#", class: "btn btn-primary btn-lg" %> 
           
        <% end %>

    </div>
</div>